Appointment.Web/Areas/Admin/Controllers/MenuController.cs
using System.Web.Mvc;

namespace Appointment.Web.Areas.Admin.Controllers
{
    public class MenuController : AdminBaseController
    {
        public ActionResult Index()
        {
            return this.View();
        }
    }
}

Appointment.Web/Areas/Appointments/Controllers/AppointmentInfoController.cs
using Appointment.Data.Filters;
using Appointment.Data.Proxies;
using Appointment.Web.Areas.Appointments.Services;
using Appointment.Web.Models;
using Microsoft.Practices.Unity;
using Newtonsoft.Json;
using System;
using System.Web.Mvc;

namespace Appointment.Web.Areas.Appointment.Controllers
{
    public class AppointmentInfoController : AppointmentBaseController
    {
        [Dependency]
        public AppointmentInfoService Service { get; set; }

        public ActionResult Index()
        {
            var model = Service.BuildModel();
            return this.View((object)JsonConvert.SerializeObject(model));
        }

        public ActionResult List()
        {
            var model = Service.BuildModel();
            return this.View((object)JsonConvert.SerializeObject(model));
        }

        [HttpPost]
        public JsonResult Get(AppointmentInfoFilter filter)
        {
            var response = new ResponseModel();

            try
            {
                response.Data = new
                {
                    Records = Service.Get(filter),
                    Count = filter.Count,
                    TotalValue = filter.TotalValue
                };
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Save(AppointmentInfoProxy proxy)
        {
            var response = new ResponseModel();

            try
            {
                Service.Save(proxy);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

Appointment.Web/Areas/Appointments/Controllers/MenuController.cs
using System.Web.Mvc;

namespace Appointment.Web.Areas.Appointment.Controllers
{
    public class MenuController: AppointmentBaseController
    {
        public ActionResult Index()
        {
            return this.View();
        }
    }
}

Appointment.Web/Areas/Appointments/Views/Menu/Index.cshtml
@using Appointment.Common;
@using Appointment.Web.Infrastructure.Bundles
@{
    ViewBag.Title = SiteMap.CurrentNode.Title;
}

@section styles {
    @Html.RenderStyles("~/Content/Menu.css")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans" rel="stylesheet">
}

<div class="row well top-bufer menu">
    <div class="row">
        <div class="col-md-10">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-4 text-center">
            <div class="icon">
                <i class="fas fa-user-friends"></i>
            </div>

            @Html.ActionLink(GlobalConstants.AddAppointment, "Index", "AppointmentInfo", null, new { @class = "link" })
        </div>

        @if (User.IsInRole(GlobalConstants.AdministratorRoleName))
        {
            <div class="col-md-4 text-center">
                <div class="icon">
                    <i class="fas fa-handshake"></i>
                </div>

                @Html.ActionLink(GlobalConstants.AppointmentControllerTitle, "List", "AppointmentInfo", null, new { @class = "link" })
            </div>
        }
    </div>
</div>