Appointment.Web/Areas/Admin/Controllers/AppointmentTypeController.cs
using Appointment.Data.Filters;
using Appointment.Data.Proxies;
using Appointment.Web.Areas.Admin.Services;
using Appointment.Web.Models;
using Microsoft.Practices.Unity;
using System;
using System.Web.Mvc;

namespace Appointment.Web.Areas.Admin.Controllers
{
    public class AppointmentTypeController : AdminBaseController
    {
        [Dependency]
        public AppointmentTypeService Service { get; set; }

        public ActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public JsonResult Get(AdminFilter filter)
        {
            var response = new ResponseModel();

            try
            {
                response.Data = Service.Get(filter);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);

            //return this.Json(new { records = result, total = filter.Count }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Upsert(AppointmentTypeProxy proxy)
        {
            var response = new ResponseModel();

            try
            {
                response.Data = Service.Upsert(proxy);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Remove(Guid id)
        {
            var response = new ResponseModel();

            try
            {
                Service.Remove(id);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

Appointment.Web/Areas/Admin/Controllers/EmployeesController.cs
using Appointment.Data.Filters;
using Appointment.Data.Proxies;
using Appointment.Web.Areas.Admin.Services;
using Appointment.Web.Models;
using Microsoft.Practices.Unity;
using System;
using System.Web.Mvc;

namespace Appointment.Web.Areas.Admin.Controllers
{
    public class EmployeesController : AdminBaseController
    {
        [Dependency]
        public EmployeeService Service { get; set; }

        public ActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public JsonResult Get(AdminFilter filter)
        {
            var response = new ResponseModel();

            try
            {
                response.Data = Service.Get(filter);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Upsert(EmployeeProxy proxy)
        {
            var response = new ResponseModel();

            try
            {
                response.Data = Service.Upsert(proxy);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Remove(Guid id)
        {
            var response = new ResponseModel();

            try
            {
                Service.Remove(id);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

Appointment.Web/Areas/Admin/Controllers/MenuController.cs
using System.Web.Mvc;

namespace Appointment.Web.Areas.Admin.Controllers
{
    public class MenuController : AdminBaseController
    {
        public ActionResult Index()
        {
            return this.View();
        }
    }
}

Appointment.Web/Areas/Admin/Controllers/PartnersController.cs
using Appointment.Data.Filters;
using Appointment.Data.Proxies;
using Appointment.Web.Areas.Admin.Services;
using Appointment.Web.Models;
using Microsoft.Practices.Unity;
using System;
using System.Web.Mvc;

namespace Appointment.Web.Areas.Admin.Controllers
{
    public class PartnersController : AdminBaseController
    {
        [Dependency]
        public PartnerService Service { get; set; }

        public ActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public JsonResult Get(AdminFilter filter)
        {
            var response = new ResponseModel();

            try
            {
                response.Data = Service.Get(filter);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);

            //return this.Json(new { records = result, total = filter.Count }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Upsert(PartnerProxy proxy)
        {
            var response = new ResponseModel();

            try
            {
                response.Data = Service.Upsert(proxy);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Remove(Guid id)
        {
            var response = new ResponseModel();

            try
            {
                Service.Remove(id);
            }
            catch (Exception ex)
            {
                response.SetException(ex);
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

Appointment.Web/Areas/Appointments/Controllers/MenuController.cs
using System.Web.Mvc;

namespace Appointment.Web.Areas.Appointment.Controllers
{
    public class MenuController: AppointmentBaseController
    {
        public ActionResult Index()
        {
            return this.View();
        }
    }
}

Appointment.Web/Areas/Admin/Views/Menu/Index.cshtml
@using Appointment.Common;
@using Appointment.Web.Infrastructure.Bundles
@{
    ViewBag.Title = SiteMap.CurrentNode.Title;
}

@section styles {
    @Html.RenderStyles("~/Content/Menu.css")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans" rel="stylesheet">
}

<div class="row well top-bufer menu">
    <div class="row">
        <div class="col-md-10">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-4 text-center">
            <div class="icon">
                <i class="fas fa-user-friends"></i>
            </div>

            @Html.ActionLink(GlobalConstants.EmployeeControllerTitle, "Index", "Employees", null, new { @class = "link" })
        </div>

        <div class="col-md-4 text-center">
            <div class="icon">
                <i class="fas fa-handshake"></i>
            </div>

            @Html.ActionLink(GlobalConstants.PartnerControllerTitle, "Index", "Partners", null, new { @class = "link" })
        </div>

        <div class="col-md-4 text-center">
            <div class="icon">
                <i class="fas fa-wallet"></i>
            </div>

            @Html.ActionLink(GlobalConstants.AppointmentTypeControllerTitle, "Index", "AppointmentType", null, new { @class = "link" })
        </div>
    </div>
</div>